start_region:
  min_limits:
    [
     0.0
    ,-2.0
    ,0.0

    ,0.0
    ,0.0
    ,3.14

    ,0.0
    ,-1.0
    ,0.0
    ]
  max_limits:
    [
     0.0
    ,-1.0
    ,1.0

    ,1.57
    ,0.0
    ,3.14

    ,0.0
    ,0.0
    ,0.0
    ]


preprocess_planner: ARAStar
# preprocess_planner: RRTConnectkConfigDefault